### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [bigeyex/python-adminui#13]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.3.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary adminui -w /tmp/ext adminui==0.3.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting adminui==0.3.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/9b3/a52c270e1c7a3/adminui-0.3.5.tar.gz (897 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-pk3p50lt/adminui/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-pk3p50lt/adminui/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-pk3p50lt/adminui/pip-egg-info
         cwd: /tmp/pip-wheel-pk3p50lt/adminui/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-pk3p50lt/adminui/setup.py", line 3, in <module>
        with open("../README.md", "r", encoding='utf-8') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '../README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bigeyex** [comment]
solved in 1.2.0
