### ISSUE TITLE
After upgrade to V1.1.0 I now get a TypeError when updating a page

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#26]
The following error is output after a page is displayed and you try to update any component on the page.
For example the following occurred when trying to use the login page.

```
[2022-05-04 11:07:01,126] ERROR in app: Exception on /api/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2126, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
10.140.9.243 - - [04/May/2022 11:07:01] "POST /api/login HTTP/1.1" 500 -
```
All pages seem to have this same error now. Seems to be a new error for V1.1.0 as this does not occur in V1.0.0

**Comment by jwag59** [comment]
Please ignore this issue.
Sorry it was my mistake ... I had forgotten to install aioflask.

**Comment by jwag59** [comment]
Perhaps you can put aioflask in the install_requires!!

**Comment by bigeyex** [comment]
hmm, it doesn't show up in my Venv's pip freeze. Are you using a virtual environment?

**Comment by jwag59** [comment]
I will close it
