### ISSUE TITLE
Working with source code in development mode

### ISSUE THREAD

**Issue by harry3689** [bigeyex/python-adminui#37]
The file _python-adminui/src/pages/Index.tsx_ should be renamed as  _python-adminui/src/pages/index.tsx_ (The I of Index.tsx should be changed to small caps i) since running npm start inside the root folder produces the following error:

```harry@harry-VirtualBox:~/test/python-adminui$ npm start

> python-adminui@0.3.9 start /home/harry/test/python-adminui
> umi dev

🚀 Starting Umi UI using umi@2.13.17...
⛽️ Ready on http://localhost:3002/
Plugin apply failed: Cannot find module '/home/harry/test/python-adminui/src/pages/index'
Require stack:
- /home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js
- /home/harry/test/python-adminui/node_modules/umi/lib/scripts/realDev.js
/home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js:314
        throw e;
        ^

Error: Cannot find module '/home/harry/test/python-adminui/src/pages/index'
Require stack:
- /home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js
- /home/harry/test/python-adminui/node_modules/umi/lib/scripts/realDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at /home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js:378:98
    at Array.reduce (<anonymous>)
    at getComponents (/home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js:376:21)
    at /home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js:383:30
    at Array.reduce (<anonymous>)
    at getComponents (/home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js:376:21)
    at Service.getRouteComponents (/home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js:390:32)
    at Array.<anonymous> (/home/harry/test/python-adminui/node_modules/umi-build-dev/lib/plugins/commands/block/ui/index.js:32:27) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/harry/test/python-adminui/node_modules/umi-build-dev/lib/Service.js',
    '/home/harry/test/python-adminui/node_modules/umi/lib/scripts/realDev.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! python-adminui@0.3.9 start: `umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the python-adminui@0.3.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harry/.npm/_logs/2022-05-10T09_19_09_508Z-debug.log```

**Comment by bigeyex** [comment]
fixed in 1.2.2
